### ISSUE TITLE
In which layer, I should integrate DB layer

### ISSUE THREAD

**Issue by aurk** [RefineriaWeb/base_app_android#2]
I'm really unable to understand complete functionality of this architecture but I want to implement this architecture in my new app because of it modularity and robustness of nature. Can you help me, how to integrate DB ?

**Comment by VictorAlbertos** [comment]
Hi.

You should integrate your DB in the data module. It is in this layer where all the stuff related with CRUD operations should be implemented. Not only persistence, but any network operation should be implemented here too. 

Personally, I would not use a DB. We use instead RxCache, both for [iOS](https://github.com/FuckBoilerplate/RxCache) and [Android](https://github.com/VictorAlbertos/RxCache) applications, which simplify the persistence process. Maybe you should give it a try ;)

**Comment by aurk** [comment]
I will have a look on RxCache but I have one question. In data module, we do not have context, so how can we integrate db layer on data module. Hope you understand my question.

**Comment by VictorAlbertos** [comment]
Yes, you can not access android context because data module is a java module, nor an android module. 

So, if you need a context -because requirements of some library you are using, it means you need to transform the data module, from a java one to an android one. 

Nevertheless, we are using now a [most simple and coupled version](https://github.com/FuckBoilerplate/base_app_android), this alternative has no separation of layers by modules, just packages. So, if you need to access the context from your data layer, this other version could be helpful for you.

**Comment by aurk** [comment]
Yes that's why I am thinking that database work should be done on presentation module. Yes, I'm using sample app as a model. However, I think that it should be done on data module that's why I am asking.

One other question is, what is the benefit of Rx-Cache over sqlite.... why should I use it... I have to justify it upper management. Basically, I'm developing quiz application in which I will use socket programming for context between two players in which I have to manage quiz, user management.. Should I use Rx-Cache or sqlite ?

Thanks for your help.

**Comment by VictorAlbertos** [comment]
Well, it's up to you ;)

But, so far, I have never found any app which could not be resolved its persistence requirements using RxCache. It is 0 configuration, easy to integrate with the networking layer (if you are using Retrofit plus observables)  and recently it provides some sort of migration system, as an actionable api to perform easily CRUD operations. 

I think Android apps as a clients app, and that's why I think using a database for Android apps is completely worthless and overkilling. But this is only my opinion, of course. 

Anyway, you should check [RxCache docs](https://github.com/VictorAlbertos/RxCache) to know it better, before taking any decision.

**Comment by aurk** [comment]
Thanks for your feedback.

**Comment by aurk** [comment]
VictorAlbertos, I have few questions again,
1. Is it possible using RX-cache to filter data like fetch all live(live = 1) record.
2. How can we sort our object on the basis of some fields.

If this is possible, then how can we achieve this. Any example will be helpful for me.

Thanks in advance.

**Comment by VictorAlbertos** [comment]
Hi @aurk 

Can you open an issue on RxCache repo with the same question, please? 

Because the issues of this repo must be related with base_app project.

Thanks.
